export default interface SymbolInfoDto {
    // symbol: string;
    // spreadInPoints: number;
    // tradeContractSize: string;
    // tradePointSize: string;
    // tradePointValue: string;
    // minPositionSize: string;
    // minPositionSizeStep: string;
    // marginByContract: string;
    // averageDailyRangeInCurrency: string;
    // marginByMinPositionSize: string;
    // spreadLossByContract: string;
    // spreadLossByMinPositionSize: string;
    // dailyMovingProfitByContract: string;
    // dailyMovingProfitByMinPositionSize: string;
    // spreadLossToMarginPercentRatio: string;
    // dailyMovingProfitToMarginPercentRatio: string;
    // dailyMovingProfitToSpreadLossRatio: string;

    symbol: string;
    bid: number;
    bidStr: string;
    ask: number;
    askStr: string;
    spreadInPoints: number;
    tradeContractSize: number;
    tradeContractSizeStr: string;
    tradePointSize: number;
    tradePointSizeStr: string;
    tradePointValue: number;
    tradePointValueStr: string;
    minPositionSize: number;
    minPositionSizeStr: string;
    minPositionSizeStep: number;
    minPositionSizeStepStr: string;
    marginByContract: number;
    marginByContractStr: string;
    averageDailyRangeInCurrency: number;
    averageDailyRangeInCurrencyStr: string;
    marginByMinPositionSize: number;
    marginByMinPositionSizeStr: string;
    spreadLossByContract: number;
    spreadLossByContractStr: string;
    spreadLossByMinPositionSize: number;
    spreadLossByMinPositionSizeStr: string;
    dailyMovingProfitByContract: number;
    dailyMovingProfitByContractStr: string;
    dailyMovingProfitByMinPositionSize: number;
    dailyMovingProfitByMinPositionSizeStr: string;
    spreadLossToMarginPercentRatio: number;
    spreadLossToMarginPercentRatioStr: string;
    dailyMovingProfitToMarginPercentRatio: number;
    dailyMovingProfitToMarginPercentRatioStr: string;
    dailyMovingProfitToSpreadLossRatio: number;
    dailyMovingProfitToSpreadLossRatioStr: string;
}